services:
  email_finder:
    image: ghcr.io/lucberge/email_finder:latest
    container_name: email_finder
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      - HOST=0.0.0.0
